### ISSUE TITLE
Blender 3.3 Support

### ISSUE THREAD

**Issue by VeissieV** [maybites/blender.script.spout#19]
Can anyone confirm if it's working for them in Blender 3.3? I don't get the sender to show up in the receiver.

**Comment by maybites** [comment]
Current master (https://github.com/maybites/blender.script.spout/releases/tag/V2.0.2) is working with blender 3.4 on my machine. Do you have any error messages in the console?

**Comment by VeissieV** [comment]
File "C:\Users\Veiss\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\spout\operators.py", line 109, in texshare_main
    spoutSender.createMemoryBuffer(context.camera.name, 1024)
AttributeError: 'SpoutGL._spoutgl.SpoutSender' object has no attribute 'createMemoryBuffer'
File "C:\Users\Veiss\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\spout\operators.py", line 88, in texshare_main

**Comment by maybites** [comment]
you pulled the latest dev-branch. and for some reason you haven't got the latest python-spout library in your search path.

for the time being please stick to master-branch and follow the instructions in the readme.
